with SUB_QUERY as(
select  YEAR(DIFFERENTIATION_DATE)  as D_YEAR,
        max(SIZE_OF_COLONY)         as M_SIZE
from    ECOLI_DATA
group by YEAR(DIFFERENTIATION_DATE)
)

select  S.D_YEAR as YEAR, S.M_SIZE-SIZE_OF_COLONY as YEAR_DEV, ID
from    ECOLI_DATA
left join SUB_QUERY as S
on      YEAR(DIFFERENTIATION_DATE) = S.D_YEAR
order by 1, 2